### ISSUE TITLE
Hanging on load for fuel tank level at zero

### ISSUE THREAD

**Issue by TheKurgan** [KSPSnark/SimpleFuelSwitch#1]
Just found a small bug, and I guess it's pretty common in my mod heavy install.

If a tank has a config like this:

RESOURCE
{
      name = Oxidizer
      amount = 0
      maxAmount = 360
}

RESOURCE
{
      name = LiquidFuel
      amount = 440
      maxAmount = 440
}

Then it hangs on game loading screen.

**Comment by TheKurgan** [comment]
So to expand on my earlier bug post, any tank that has the amount less then the max amount causes the hang. Like in the resource config below from Large Boat parts:

RESOURCE
    {
        name = LiquidFuel
        amount = 1000
        maxAmount = 18000
    }

**Comment by KSPSnark** [comment]
This was fixed with release 1.0.1. Thank you for the report, never got around to closing.  ;-)
